FROM node:18-alpine

# Set working directory
WORKDIR /

# Install dependencies
COPY package*.json ./

RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Expose the port that Vite's server runs on
EXPOSE 3000

# Command to start the Vite server
CMD ["npm", "run", "dev"]